apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-model
  template:
    metadata:
      labels:
        app: custom-model
    spec:
      containers:
      - name: custom-model-container
        image: gcr.io/nileshproject-435805/airflow_iris_model:latest 
        ports:
        - containerPort: 5000
        imagePullPolicy: Always

# Service definition
---
apiVersion: v1
kind: Service
metadata:
  name: custom-model-service
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500
  selector:
    app: custom-model